[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = []
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200

[profile.ci]
verbosity = 4

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
localhost = "http://localhost:8545"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }